export const PC_LIST_REQUEST = 'PC_LIST_REQUEST'
export const PC_LIST_SUCCESS = 'PC_LIST_SUCCESS'
export const PC_LIST_FAIL = 'PC_LIST_FAIL'

export const PC_DETAIL_REQUEST = 'PC_DETAIL_REQUEST'
export const PC_DETAIL_SUCCESS = 'PC_DETAIL_SUCCESS'
export const PC_DETAIL_FAIL = 'PC_DETAIL_FAIL'

export const NPC_LIST_REQUEST = 'NPC_LIST_REQUEST'
export const NPC_LIST_SUCCESS = 'NPC_LIST_SUCCESS'
export const NPC_LIST_FAIL = 'NPC_LIST_FAIL'

export const NPC_DETAIL_REQUEST = 'NPC_DETAIL_REQUEST'
export const NPC_DETAIL_SUCCESS = 'NPC_DETAIL_SUCCESS'
export const NPC_DETAIL_FAIL = 'NPC_DETAIL_FAIL'
